version: '3.7'

services:
  mongo_master:
    container_name: mongo_master
    image: mongo:4.4
    volumes:
      - ./data:/data/db
      - ./rs-init.sh:/scripts/rs-init.sh
      - ./mongod.conf:/etc/mongod.conf.orig
      - ./log:/var/log/mongodb
#    networks:
#      - mongors-network
    ports:
      - 27017:27017
#    links:
#      - mongo2
#      - mongo3
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "cqstation" ]
#  mongo2:
#    container_name: mongo2
#    image: mongo:4.4
#    volumes:
#      - ./data2:/data/db
#    networks:
#      - mongors-network
#    ports:
#      - 27022:27017
#    restart: always
#    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
#  mongo3:
#    container_name: mongo3
#    image: mongo:4.4
#    volumes:
#      - ./data3:/data/db
#    networks:
#      - mongors-network
#    ports:
#      - 27023:27017
#    restart: always
#    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

#networks:
#  mongors-network:
#    driver: bridge
