version: '3.7'

services:
#  mongo_master:
#    container_name: mongo_master
#    image: mongo:4.4
#    volumes:
#      - ./data1:/data/db
#      - ./rs-init.sh:/scripts/rs-init.sh
#    networks:
#      - mongors-network
#    ports:
#      - 27021:27017
#    links:
#      - mongo_slave
#      - mongo3
#   restart: always
#    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  mongo_slave:
    container_name: mongo_slave
    image: mongo:4.4
    volumes:
      - ./data:/data/db
      - ./log:/var/log/mongodb
      - ./mongod.conf:/etc/mongod.conf.orig
#    networks:
#      - mongors-network
    ports:
      - 27017:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "cqstation" ]
#  mongo3:
#    container_name: mongo3
#    image: mongo:4.4
#    volumes:
#      - ~/mongors/data3:/data/db
#    networks:
#      - mongors-network
#    ports:
#      - 27023:27017
#    restart: always
#    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

#networks:
#  mongors-network:
#    driver: bridge
